insert into events (event_date, title, description, location, tickets, category_id) values ('2025-04-29 15:53:03', 'Rocketship X-M', 'Durable, unbreakable wine glasses for outdoor use.', 'Gomel', 5, 3);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-05-25 06:19:48', 'The Breed', 'Crispy chips made from taro root, a wonderful snack.', 'Luyi', 1, 1);
insert into events (event_date, title, description, location, tickets, category_id) values ('2025-01-10 17:19:46', 'Stray Dogs', 'Stylish stand to hold your recipes while cooking.', 'Golek', 2, 3);
insert into events (event_date, title, description, location, tickets, category_id) values ('2025-03-14 14:07:16', 'The Kings of Mykonos', 'Relaxing paint kit with pre-printed canvas for painting.', 'Fomento', 2, 2);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-06-14 02:05:00', 'Lord Love a Duck', 'Organize your board games with this storage bin.', 'Malax', 2, 1);
insert into events (event_date, title, description, location, tickets, category_id) values ('2025-03-07 02:03:35', 'Late Marriage (Hatuna Meuheret)', 'Juicy peach slices in light syrup, in convenient cups.', 'Biankouma', 1, 2);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-06-24 20:54:18', 'Kaena: The Prophecy (Kaena: La prophétie)', 'Spicy and creamy dip made with shredded chicken, perfect for parties.', 'Duanjia', 5, 4);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-08-29 19:25:22', 'The Amazing Catfish', 'Quick oatmeal packets infused with apple and cinnamon, perfect for breakfast.', 'Kuluran', 3, 2);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-11-20 09:44:17', 'Cashback', 'Freshly baked artisan bread with a crisp crust and soft center.', 'Malaga', 1, 4);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-09-21 01:14:37', 'Riley Rewind', 'Comfortable camping mattress that inflates automatically.', 'Kangdong-ŭp', 2, 1);
insert into events (event_date, title, description, location, tickets, category_id) values ('2025-04-03 20:40:07', 'Memory Lane', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Yeshan', 4, 1);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-08-13 04:06:08', 'Pump Up the Volume', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Hujra', 4, 2);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-12-15 05:47:22', 'History of the Eagles', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Nilanapo', 2, 2);
insert into events (event_date, title, description, location, tickets, category_id) values ('2025-05-15 23:26:10', 'Blonde Crazy', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Long’an Chengxiangzhen', 3, 3);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-08-15 10:26:30', 'Last Summer of La Boyita, The (El último verano de la Boyita)', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Tatariv', 3, 3);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-05-31 04:04:56', 'The Beast of the City', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Khasht’arrak', 1, 1);
insert into events (event_date, title, description, location, tickets, category_id) values ('2025-04-03 12:27:46', 'Hillbillys in a Haunted House', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Pinar del Río', 2, 4);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-11-03 13:55:04', 'Hôtel du Nord', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Reno', 2, 2);
insert into events (event_date, title, description, location, tickets, category_id) values ('2024-06-27 21:56:50', 'So Close (Chik Yeung Tin Sai)', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Kaynardzha', 5, 3);



