services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      TZ: 'Europe/Rome'
    #ports:
    #  - "${DB_PORT}:3306"
    volumes:
      - ${PROJECT_ROOT}/mariadb-init:/docker-entrypoint-initdb.d:ro # Place init .sql file(s) here.
      - mariadb:/var/lib/mysql
    secrets:
      - db_root_password
      - db_name
      - db_user
      - db_password

  php:
    image: wodby/php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    depends_on:
    - mariadb
    environment:
      # By default xdebug extension also disabled.
      PHP_EXTENSIONS_DISABLE: xhprof,spx
      PHP_MAIL_MIXED_LF_AND_CRLF: 'On'
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_FPM_CLEAR_ENV: 'yes'
      PHP_DATE_TIMEZONE: 'Europe/Rome'
      PHP_SESSION_USE_ONLY_COOKIES: 'On'
      PHP_SESSION_USE_COOKIES: 'On'
      PHP_SESSION_REFERER_CHECK: 'localhost'
      PHP_SESSION_USE_TRANS_SID: 'Off'
      PHP_ERROR_REPORTING: 'Off'
      TZ: 'Europe/Rome'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html:cached
    secrets:
      - db_host
      - db_name
      - db_user
      - db_password
      - php_pepper
      - php_secret

  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: "${PROJECT_NAME}_apache"
    depends_on:
    - php
    environment:
      APACHE_LOG_LEVEL: error
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html/app
      APACHE_USER: wodby
      TZ: 'Europe/Rome'
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html:ro
      - ${PROJECT_ROOT}/apache-conf/vhost-ssl.conf:/usr/local/apache2/conf/conf.d/vhost-ssl.conf:ro
      - ${PROJECT_ROOT}/apache-ssl/:/usr/local/apache2/conf/ssl:ro

volumes:
  mariadb:

secrets:
  db_host:
    environment: "DB_HOST"
  db_name:
    environment: "DB_NAME"
  db_user:
    environment: "DB_USER"
  db_password:
    environment: "DB_PASSWORD"
  db_root_password:
    environment: "DB_ROOT_PASSWORD"
  php_pepper:
    environment: "PHP_PEPPER"
  php_secret:
    environment: "PHP_SECRET"